name: Build Utopia Component in Native Environment

on:
  push:
    branches: [ main, 'sprint/**', 'release/**', develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', topic/RDK*, develop ]

jobs:
  build-utopia-on-pr:
    name: Build utopia component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: native build
        run: |
          chmod +x cov_docker_script/setup_dependencies.sh
          ./cov_docker_script/setup_dependencies.sh
          chmod +x cov_docker_script/build_native.sh
          ./cov_docker_script/build_native.sh

        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}
